### ISSUE TITLE
Contribuidor

### ISSUE THREAD

**Issue by hgees** [tonyfrance/informatica29NatalComVelha#1]
Confirmem aqui que foram adicionados

**Comment by tonyfrance** [comment]
certo

**Comment by drbeco** [comment]
label/milestones

**Comment by tonyfrance** [comment]
todos os contribuidores foram adicionados.

**Comment by hgees** [comment]
Ainda faltam contribuidores confirmarem se foram adicionados

**Comment by tonyfrance** [comment]
hericles eles comentaram alguns issues e fizeram commit
