### ISSUE TITLE
Quadrado mágico

### ISSUE THREAD

**Issue by drbeco** [tonyfrance/informatica29NatalComVelha#10]
Vocês sabem o que é na matemática um **quadrado mágico**?

E qual a relação que tem com o jogo-da-velha?

![image](https://cloud.githubusercontent.com/assets/5805111/11985064/d6dd5430-a99f-11e5-95be-b929a642fd23.png)

**Comment by priscilasousa** [comment]
Não sei a relação do quadrado mágico com o jogo-da-velha, mas sei que no quadrado mágico a soma das linhas, colunas e diagonais tem que ser igual a 15.

**Comment by tonyfrance** [comment]
priscila, penso  que ele quis dizer que quando a linha,coluna ou diagonal der 15 significa que voce ganhou.

**Comment by priscilasousa** [comment]
No caso do quadrado mágico tem que ser as linhas e as colunas e as diagonais somando cada uma 15, no caso do jogo-da-velha é um ou outro. Acho também que é essa a relação.

**Comment by hgees** [comment]
Num quadrado magico a soma das colunas, linhas e diagonais devem dar um numero em comum que não tem necessidade de ser 15 porém eu não sei qual sua relação com o jogo da velha.
