### ISSUE TITLE
bug na funcao vence

### ISSUE THREAD

**Issue by tonyfrance** [tonyfrance/informatica29NatalComVelha#17]
quando estar no modo de pc vs pc no modo facil, esta o correndo o erro.
![image](https://cloud.githubusercontent.com/assets/14056066/12008280/3eb268d0-ac10-11e5-80eb-921cac8223fb.png)

**Comment by tonyfrance** [comment]
eu to testando e vi que o erro esta nessas casas X 0,0 X 1,1 O 2,2

**Comment by tonyfrance** [comment]
o erro esta nas duas diagonais

**Comment by hgees** [comment]
creio que fazendo um **if** separado pra cada caso resolveria este problema

**Comment by hgees** [comment]
como dito, Resolvido.
