### ISSUE TITLE
Adicionar AUTHORS

### ISSUE THREAD

**Issue by hgees** [tonyfrance/informatica29NatalComVelha#2]
fazer o arquivo AUTHORS contendo o nome e contato de cada integrante

**Comment by tonyfrance** [comment]
Ok,
quando um esquecer lembrar que cada issues tem que por label e milestone.

**Comment by tonyfrance** [comment]
podemos colocar os autores no **README.md**

**Comment by drbeco** [comment]
Pode sim, mas tem que ter o arquivo AUTHORS de qualquer forma.

O README é mais um manual de como usar o programa.

**Comment by tonyfrance** [comment]
obrigado ja que vai ter que por o **AUTHORS** entao e melhor colocar os autores la mesmo

**Comment by tonyfrance** [comment]
**AUTHORS**  finalizado
