### ISSUE TITLE
Jogo nao vence ?! O.o

### ISSUE THREAD

**Issue by thiagooqueiroz** [tonyfrance/informatica29NatalComVelha#23]
Gente o seguinte :
qnd o player fecha uma linha , o jogo não indica o vencedor(mesmo tendo uma função para isso) ...mas continua rodando até q termine de preencher o tabuleiro....
Então solicito ajuda dos colaboradores para solucionar esse erro... :+1:

**Comment by tonyfrance** [comment]
esta feito.
