### ISSUE TITLE
Niveis de dificuldade

### ISSUE THREAD

**Issue by hgees** [tonyfrance/informatica29NatalComVelha#24]
Precisamos implementar os niveis medio e dificil nos modos pcVSpc e humanoVSpc mas como fazer isso? gostaria da ajuda de todos.

**Comment by tonyfrance** [comment]
estamos pensando nisso.

**Comment by priscilasousa** [comment]
vamos pensar num jeito de fazer esse programa rodar, completo!

**Comment by hgees** [comment]
Parece que o @tonyfrance já implementou o nivel medio restando para nós procurar bugs nesse nivel e implementar o nivel dificil. vamos lá!!

**Comment by tonyfrance** [comment]
como ja esta feito o nivel medio e dificil, fechado
