### ISSUE TITLE
bug na funcao vence

### ISSUE THREAD

**Issue by tonyfrance** [tonyfrance/informatica29NatalComVelha#28]
galera a funcao vence esta com um bug e nao estou conseguindo ajeitar

**Comment by tonyfrance** [comment]
fiz uma alteracao, deixei o codigo original como comentario caso essa minha alteraçao nao seja do agrado de vcs respodam o mais rapido possivel.

**Comment by hgees** [comment]
a nova função vence está funcionando perfeitamente
