### ISSUE TITLE
impressão da tabela três vezes na mesma jogada

### ISSUE THREAD

**Issue by priscilasousa** [tonyfrance/informatica29NatalComVelha#29]
A cada jogada, a tabela é impressa três vezes com a mesma marcação (X), na mesma lacuna.

**Comment by hgees** [comment]
Creio que isso se deve pelo fato da função **imprimetab** estar sendo chamada 3 vezes. vemos procurar onde e retirar este problema.

**Comment by tonyfrance** [comment]
estamos trabalhando nisso.
