### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by hgees** [tonyfrance/informatica29NatalComVelha#3]
Vamos discutir aqui a data da milestone intermediaria.
Em qual ata vocês acham melhor colocá-la?

**Comment by drbeco** [comment]
Todo issue deve ter label e milestone. Não gostaria de ter que ficar lembrando disso o tempo todo.

**Comment by hgees** [comment]
Desculpem todos, não tinha notado que a milestone v0.2 tinha uma data fixa.
Ela fica pro dia 26/12.
Desculpas novamente.

**Comment by tonyfrance** [comment]
sim pode deixar pro dia 26 mesmo
