### ISSUE TITLE
wiki criada

### ISSUE THREAD

**Issue by priscilasousa** [tonyfrance/informatica29NatalComVelha#30]
Gente, criei a wiki, gostaria que vocês fossem dar uma olhada pra ver se ficou legal, ou se podemos colocar mais alguma coisa para implementar. Grata.

**Comment by tonyfrance** [comment]
vamos criar mais uma page falando do nosso codigo.

**Comment by priscilasousa** [comment]
ta certo Tony, é bom colocar sobre nosso código.

**Comment by hgees** [comment]
Muito obrigado, Priscila. ficou muito bom
