### ISSUE TITLE
Milestones com data errada

### ISSUE THREAD

**Issue by drbeco** [tonyfrance/informatica29NatalComVelha#4]
Os três milestones que dei no email com a descrição do problema são obrigatórios e devem ter a data correta.

Isso faz parte da tarefa da versão v0.1

Aqui o erro:
![image](https://cloud.githubusercontent.com/assets/5805111/11943236/f707f69c-a81a-11e5-8cb1-8391cd16224c.png)

Aqui o que deveria estar:

```
Releases (milestones):
v0.1 - 22/Dez/15 - esqueleto e todos arquivos, AUTHORS definido, todos colaboradores adicionados (eu inclusive)
v0.2 - 26/Dez/15 - versão funcionando o nível 1 - fácil
v1.0 - 28/Dez/15 - versão final
```

**Comment by hgees** [comment]
Obrigado Professor, não tinha reparado isso.
Corrigido
