### ISSUE TITLE
Melhorar o README.md

### ISSUE THREAD

**Issue by drbeco** [tonyfrance/informatica29NatalComVelha#5]
Este arquivo é normalmente uma descrição do programa, uma ajuda ou manual.

**Comment by tonyfrance** [comment]
no decorrer do programa iremos adicionando o conteúdo.

**Comment by drbeco** [comment]
Mantenha aberto até o dia da v0.2 - data limite para resolver este bug.

**Comment by hgees** [comment]
Por favor colaboradores, adicionem seus nomes no arquivo README.

**Comment by tonyfrance** [comment]
nao precisa hericles ja foi adicionado nos **AUTHORS**

**Comment by drbeco** [comment]
![image](https://cloud.githubusercontent.com/assets/5805111/11985010/7181bf5e-a99f-11e5-8043-3fd3ac3d6ad9.png)

O tabuleiro está todo errado (veja imagem)

**Comment by hgees** [comment]
Professor,  gostariamos de alguma ajuda com esse README pois no VI nós pulamos as linhas corretamente porém no git elas não são puladas... se alguém tiver uma maneira de arrumar isso eu ficaria agradecido.

**Comment by drbeco** [comment]
![image](https://cloud.githubusercontent.com/assets/5805111/11985147/9e93df08-a9a0-11e5-9eec-d33bab47933f.png)

**Comment by hgees** [comment]
Obrigado professor, foi de grande ajuda.

**Comment by hgees** [comment]
Encontrada uma solução para o problema.

**Comment by drbeco** [comment]
Vocês apagaram o tabuleiro?

**Comment by hgees** [comment]
Sim, pois o mesmo foi incorporado ao código

**Comment by drbeco** [comment]
O que tem a ver o README com o código?

O README é a página da web que as pessoas vêem quando chegam no site (home page).

**Comment by hgees** [comment]
:+1:

**Comment by hgees** [comment]
| 1 | 2 | 3 |
|---|---|---|
| 4 | 5 | 6 |
|---|---|---|
| 7 | 8 | 9 |

**Comment by priscilasousa** [comment]
Tabela feita!
