### ISSUE TITLE
Representação tab[3][3] (não tab[9])

### ISSUE THREAD

**Issue by drbeco** [tonyfrance/informatica29NatalComVelha#6]
Mudar a representação do tabuleiro para:

```
int nivelfacil(int tab[3][3], int vez); /* nivel facil */
int nivelmedio(int tab[3][3], int vez); /* nivel medio */
int niveldificil(int tab[3][3], int vez); /* nivel dificil */
```

**Comment by tonyfrance** [comment]
consertado.

**Comment by tonyfrance** [comment]
desculpe professor, não tinha lido que era para deixar aberto ate a data limite do fechamento da milestone

**Comment by hgees** [comment]
Tony, como este bug já foi resolvido pode sim fechá-lo.

**Comment by tonyfrance** [comment]
no outro issues ele fala isso, lê la o issues #5 (basta clicar no #5)

**Comment by priscilasousa** [comment]
Verdade Hericles, é isso mesmo Tony.
